using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SpawnManager : MonoBehaviour
{
    public GameObject wood;
    public GameObject stone;

    public int randomLocationX;
    public int randomLocationy;

    Vector2 vector1;
    // Start is called before the first frame update
    void Start()
    {
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood,new Vector2(randomLocationX,randomLocationy),Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(wood, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);


        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);
        randomLocationy = Random.Range(10, -12);
        randomLocationX = Random.Range(-35, 32);
        print(randomLocationX);
        print(randomLocationy);
        Instantiate(stone, new Vector2(randomLocationX, randomLocationy), Quaternion.identity);



    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
